name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: prepare docker daemon
        run: |
          apt-get update -q
          apt-get install -yq qemu-user-static qemu binfmt-support
          update-binfmts --display
          mkdir -p ~/.docker/cli-plugins/
          wget https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64 -O ~/.docker/cli-plugins/docker-buildx
          chmod a+x ~/.docker/cli-plugins/docker-buildx
          echo '{"max-concurrent-downloads": 5, "experimental": true}' > /etc/docker/daemon.json
          systemctl restart docker
          docker buildx ls
          docker buildx create --use --name mybuilder
          docker buildx inspect --bootstrap
          docker buildx ls

#     - name: Run a one-line script
#       run: export
